module.exports = function () {
  console.log('Welcome to CreactJs');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs init <newModuleName>');
  console.log('');
  console.log('-s -store  -> create a store');
  console.log('-v -view  -> creates a view element');
  console.log('');
  console.log('* This function will initialize an empty react view/store');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs publish');
  console.log('');
  console.log('* This function will publish your module to CreactJs');
  console.log('* creact.json required with a unique name');
  console.log('* you must add a valid user before publishing');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs install');
  console.log('');
  console.log('* This function will install all dependencies described in the creact.json');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs install <moduleName>');
  console.log('');
  console.log('* This function will install the module and add the dependency in the creact.json');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs remove <moduleName>');
  console.log('');
  console.log('* This function will remove the module and remove the dependency in the creact.json');
  console.log('');
  console.log('==================================');
  console.log('');
  console.log('$ cjs setuser <username>');
  console.log('');
  console.log('* First register a user on www.creactjs.org');
  console.log('* This function will record the user name and password and it will use them to publish the modules');
  console.log('* If a user exists it will override the previous setting');
  console.log('');

};